---
- name: Windows account creation
  hosts: windemo

  pre_tasks:
    - name: Create change request
      tags: snow
      register: r_chg_req
      delegate_to: localhost
      servicenow.itsm.change_request:
        type: standard
        state: new
        requested_by: service.ansible
        short_description: Windows Account Creation
        description: "Inventory hostname: {{ inventory_hostname }}"
        category: system_software
        priority: moderate
        risk: low
        impact: low
        other:
          cmdb_ci: "{{ my_server }}"

    - name: Update change request status
      tags: snow
      delegate_to: localhost
      servicenow.itsm.change_request:
        number: "{{ r_chg_req.record.number }}"
        state: scheduled
        assignment_group: Ansible West Tigers

    - name: Update change request status
      tags: snow
      delegate_to: localhost
      servicenow.itsm.change_request:
        number: "{{ r_chg_req.record.number }}"
        state: implement

    - name: Generate work dates
      ansible.builtin.set_fact:
        planned_start_date: "{{ lookup('pipe', 'date +\"%Y%m%d %H:%M:%S\"') }}"
        planned_end_date: "{{ lookup('pipe', 'date -d \"+30 minutes\" +\"%Y%m%d %H:%M:%S\"') }}"

    - name: Create a change task
      tags: snow
      delegate_to: localhost
      register: r_chg_task
      servicenow.itsm.change_request_task:
        configuration_item: "{{ my_server }}"
        change_request_number: "{{ r_chg_req.record.number }}"
        type: implementation
        state: open
        assigned_to: service.ansible
        short_description: "creating accounts on {{ inventory_hostname }}"
        description: "starting account creation @ {{ planned_start_date }}"
        planned_start_date: "{{ planned_start_date }}"
        planned_end_date: "{{ planned_end_date }}"
        other:
          approval: approved

  roles:
    - role: windows_account_create

  post_tasks:
    - name: Close a change task | successful
      tags: snow
      delegate_to: localhost
      servicenow.itsm.change_request_task:
        number: "{{ r_chg_task.record.number }}"
        state: closed
        close_code: successful
        close_notes: "{{ r_windows_accounts.results | ansible.utils.remove_keys(target=['item','invocation']) | to_nice_yaml }}"

    - name: Update change request status | review
      tags: snow
      delegate_to: localhost
      servicenow.itsm.change_request:
        number: "{{ r_chg_req.record.number }}"
        state: review

    - name: Close change request | successful
      tags: snow
      delegate_to: localhost
      servicenow.itsm.change_request:
        number: "{{ r_chg_req.record.number }}"
        state: closed
        close_code: successful
        close_notes: Closed